<?php

/**
 * @file
 * Functions to support theming in the my_bootstrap_subtheme theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function my_bootstrap_subtheme_preprocess_html(array &$variables) {
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function my_bootstrap_subtheme_preprocess_page(array &$variables) {
}

/**
 * Implements hook_preprocess_node().
 */
function my_bootstrap_subtheme_preprocess_node(array &$variables) {
}
